# Netlify configuration for Multi-Deck German Learning App

[build]
  publish = "."

# Optimize audio file caching
[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
    
# Optimize JSON file caching
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "max-age=3600"
    
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
